### ISSUE TITLE
Rename the project name from IBAnimatable-Material to IBAnimatableMaterial?

### ISSUE THREAD

**Issue by JakeLin** [JakeLin/IBAnimatable-Material#17]
Since we have framework `IBAnimatableMaterial.framework` and CocoaPods `IBAnimatableMaterial`, I am thinking we should rename it to `IBAnimatableMaterial`.

In the future, all plugins are named `IBAnimatable<CoolStuff>`

Can you guys provide some feedback on this? @damtsnkff @gkye @tbaranes

**Comment by JakeLin** [comment]
Please 👍 if we keep `IBAnimatable-Material` and use `IBAnimatable-<CoolStuff>` for all plugins.

**Comment by JakeLin** [comment]
Please 👍 if we want to change to `IBAnimatableMaterial` and use `IBAnimatable<CoolStuff>` for all plugins.

**Comment by gkye** [comment]
Name change to IBAnimatableMaterial sounds good but I'm on the fence about renaming  the plugins to `IBAnimatable<CoolStuff>` (users need to be able to differentiate between the plugins offered by `IBAnimatable` and those offered by `IBAnimatableMaterial`)

**Comment by damtsnkff** [comment]
@gkye what kind of plugins were you thinking about for IBAnimatableMaterial ?

**Comment by tbaranes** [comment]
Everyone agree about the naming, awesome! 🎉

**Comment by gkye** [comment]
@damtsnkff the elements stated here https://github.com/JakeLin/IBAnimatable-Material/issues/7 unless @JakeLin is referring to something else? (If so disregard that comment)

**Comment by JakeLin** [comment]
@gkye I was thinking some like `IBAnimatableFontAwesome`... Similar to `IBAnimatableMaterial`.

If we all agree with the new name? Shall we do it now or when we move to `IBAnimatable` organization?

**Comment by gkye** [comment]
Okay cool :smile_cat: and whatever the group thinks is better

**Comment by tbaranes** [comment]
@JakeLin Let's change it once it's moved in the organisation. Let's have all the breaking change at the same time.

**Comment by JakeLin** [comment]
I have submitted a PR #18 since we haven't released yet, no breaking changes 😁

**Comment by tbaranes** [comment]
At least wait before changing the repository name 😈

**Comment by JakeLin** [comment]
Will wait @tbaranes 😊

**Comment by gkye** [comment]
Should all elements be renamed from `AnimatableMaterial` to `IBAnimatableMaterial`?
