### ISSUE TITLE
Create a Framework target and an App target

### ISSUE THREAD

**Issue by JakeLin** [JakeLin/IBAnimatable-Material#3]
Framework target is used for package management tools like CocoaPods, Carthage to distribute the framework.

App target is used for the demo app.

**Comment by damtsnkff** [comment]
@JakeLin @gkye Sorry guys I was busy for the release of my app last week. I'll do that today if it's good for you two

**Comment by JakeLin** [comment]
@damtsnkff No worries, only when you are free, we don't have any obligation to work on the project. Only when we are free and interested in the features. Let's have some fun 💃

**Comment by damtsnkff** [comment]
See #14
